# Merge IRGA72 fluxes + meteo 7 (2016-2024)

# Imports

In [1]:
import importlib.metadata
import pandas as pd
import warnings
from datetime import datetime
from pathlib import Path

from diive.core.io.filereader import search_files, MultiDataFileReader
from diive.core.io.files import save_parquet, load_parquet
# pd.options.display.width = None
# pd.options.display.max_columns = None
pd.set_option('display.max_rows', 3000)
pd.set_option('display.max_columns', 3000)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.89.0

# Load data: fluxes L1 and meteo (7 variables)

In [2]:
irga72 = load_parquet(filepath="22.2_FLUXES_IRGA72_L1_2016-2024.parquet")
meteo7 = load_parquet(filepath=Path("../10_METEO/") / "12.5_METEO7_GAPFILLED_2004-2024.parquet")

Loaded .parquet file 22.2_FLUXES_IRGA72_L1_2016-2024.parquet (0.338 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ..\10_METEO\12.5_METEO7_GAPFILLED_2004-2024.parquet (0.192 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# Merge files

## Start with IRGA data

In [3]:
df = irga72.copy()
df

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INST_AVERAGING_INT,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_HEIGHT_SA,BADM_INST_SAMPLING_INT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AGC_IRGA75_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_AIR_P_MEAN_1,CUSTOM_AIR_P_MEAN_2,CUSTOM_AIR_T_MEAN,CUSTOM_CO2_MEAN,CUSTOM_CO2_MEAN_1,CUSTOM_CO2_MEAN_2,CUSTOM_COOLER_V_IRGA72_MEAN,CUSTOM_COOLER_V_IRGA75_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_IRGA75_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FLOW_VOLRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA75_MEAN,CUSTOM_H2O_MEAN,CUSTOM_H2O_MEAN_1,CUSTOM_H2O_MEAN_2,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA75_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILE_NR,FILE_TIME_DURATION,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_SA,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,NIGHT,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA_CELL,PA_EP,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_SA,RH_EP,ROT_PITCH,ROT_YAW,ROUGHNESS_LENGTH,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SW_IN_POT,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_EP,TDEW,TIMELAG_DETECTION_METHOD,TIMESTAMP_START,TKE,TSTAR,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_SA,VPD_EP,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-01-11 15:45:00,1005.20,1.17718,0.024605,1183.30,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,50.0,NaN,90499.5,NaN,281.278,NaN,15.5440,NaN,NaN,1.27544,NaN,2.0,16.0,36000.0,0.0,NaN,NaN,248.0,NaN,356.650,NaN,NaN,200.0,0.0,0.0,0.0,24.79,11.6665,11.6457,1.17718,0.024605,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.2995,72.9598,111.2680,156.055,186.758,233.799,85.3546,-12.95290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,-67.51970,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.026258,35571.0,2.31809,12.2068,1.00552,18.0,0.0,2.0,-67.14910,-67.14910,-67.14910,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2344.180,2337.810,NaN,NaN,0.0,6.0,18.0,93.1361,93.1361,NaN,NaN,0.02,NaN,13.25440,147.3260,5.55,NaN,0.000000,NaN,NaN,NaN,0.0,35571.0,2494250.0,NaN,4.0,150.38700,-1.813790,0.030202,35571.0,1.146500,0.190990,1.00549,3.0,0.0,1.0,-1.813790,-1.813790,-1.803880,2.483100,NaN,2.0,2.016011e+11,6.08317,-0.045969,2.483100,11.55750,0.0,5.0,1.0,9.55246,3.98173,0.0,11.57000,36000.0,10.0,11.41000,11.69000,0.246934,0.175244,14.0,800000011.0,2921.0,7.54906,1.241290,1.237890,0.0,9.0,1.0,5.89282,2.51007,1.50,7.54336,0.0,5.65402,9.35414,2.45878,0.101771,0.0,-6.189200,800000000.0,0.0,4.057320e-14,NaN,NaN,NaN,NaN,80.0,80.0,80000.0,80000.0,NaN,NaN,12.5,NaN,0.0,7.48225,2.92124,1.50,0.024833,5.0,-1.367950,1.392650,1.98752,-0.062275,6.0,3.96221,800000000.0,11.0,-1.746930e-14,0.0,241.971,36000.0,0.0,16.5027,0.0,7.54906,16.93280,0.0,NaN,NaN,4.0,1.0,7.65689,3.10296,1.50,0.134054,1.0,-0.972546,1.067220,1.473260,-0.413131,1.0,-0.056747,-0.048156,-0.005825,-0.012614,-0.019363,-0.025539,-0.030982,-0.035778,-0.039816,-0.042933,-0.045455,1.730810,-1.432500,801010000.0,0.0,0.009475,0.009500
2016-01-11 16:15:00,1005.19,1.17833,0.024581,1184.45,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,50.0,NaN,90523.6,NaN,281.370,NaN,15.5503,NaN,NaN,1.27298,NaN,2.0,16.0,36000.0,0.0,NaN,NaN,248.0,NaN,356.087,NaN,NaN,200.0,0.0,0.0,0.0,24.79,11.6873,11.6665,1.17833,0.024581,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.7332,74.0399,112.9160,158.366,189.523,237.261,86.6182,-13.14460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,-110.23300,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.030431,35415.0,3.55234,54.0496,1.00594,114.0,2.0,6.0,-109.58200,-109.58200,-109.58200,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2400.290,2396.100,NaN,NaN,0.0,6.0,18.0,93.1361,93.1361,NaN,NaN,0.02,NaN,6.65637,133.4050,5.55,NaN,NaN,NaN,-8.29769,NaN,0.0,35415.0,2494890.0,NaN,4.0,53.50470,-2.557300,0.019622,35415.0,1.553280,0.216385,1.00513,1.0,0.0,1.0,-2.557300,-2.557300,-2.544250,2.214800,NaN,2.0,2.016011e+11,8.91238,-0.063174,2.214800,12.61110,0.0,78.0,5.0,5.04625,2.03169,0.0,12.67000,36000.0,9.0,12.14000,13.04000,0.582354,0.011791,9.0,800000000.0,1713.0,9.08330,1.473180,1.469420,0.0,1.0,1.0,5.86540,2.77295,1.55,8.83618,0.0,6.92066,11.07750,3.06380,0.313824,0.0,-6.229790,800000001.0,0.0,-2.601460e-13,NaN,NaN,NaN,NaN,80.0,80.0,80000.0,80000.0,NaN,NaN,12.5,NaN,0.0,6.57912,3.63431,1.55,-0.105979,6.0,-1.438440,1.450290,2.34304,0.045284,10.0,6.54971,800000001.0,8.0,-2.546370e-13,0.0,255.937,36000.0,0.0,15.4760,0.0,9.08330,20.34650,0.0,NaN,NaN,6.0,1.0,7.31186,2.68205,1.55,0.148362,0.0,-1.272560,1.260830,1.716980,-0.219736,0.0,-0.092517,-0.141366,-0.117904,-0.126720,-0.129359,-0.129270,-0.129434,-0.131085,-0.133574,-0.136176,-0.138733,1.052890,-1.801750,801010000.0,0.0,0.009253,0.009269
2016-01-11 16:45:00,1005.19,1.17813,0.024585,1184.25,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,50.0,NaN,90590.3,NaN,280.954,NaN,15.6039,NaN,NaN,1.26624,NaN,2.0,16.0,36000.0,0.0,NaN,NaN,248.0,NaN,350.531,NaN,NaN,200.0,0.0,0.0,0.0,24.79,11.7082,11.6873,1.17813,0.024585,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.4718,80.8594,123.3160,172.952,206.979,259.114,94.5962,-14.35530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,221.79600,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.012436,35995.0,1.19103,95.4255,1.01008,21.0,0.0,2.0,219.58300,219.58300,219.58300,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-854.592,-846.400,NaN,NaN,1.0,6.0,18.0,93.1361,93.1361,NaN,NaN,0.02,NaN,9.00528,134.9820,5.55,NaN,NaN,NaN,1.41807,NaN,0.0,35995.0,2494780.0,NaN,4.0,1.47103,-2.047090,0.050452,35995.0,1.759160,0.173897,1.01320,13.0,0.0,1.0,-2.047090,-2.047090,-2.020420,2.260660,NaN,2.0,2.016011e+11,4.48263,0.142083,2.260660,13.42850,0.0,180.0,6.0,112.93400,18.20790,0.0,13.75000,36000.0,13.0,13.49000,13.90000,1.227920,-3.851710,14.0,800001101.0,2944.0,5.91130,1.318160,1.309550,0.0,26.0,2.0,6.72775,3.16019,0.10,5.72315,0.0,4.36682,7.26770,2.06750,0.522574,0.0,-4.126890,800000000.0,1.0,-1.707120e-13,NaN,NaN,NaN,NaN,80.0,80.0,80000.0,80000.0,NaN,NaN,12.5,NaN,0.0,6.97967,3.21268,0.10,0.059190,15.0,-1.030770,1.125750,1.67695,-0.275722,22.0,4.12997,800000001.0,28.0,1.973850e-13,0.0,253.310,36000.0,0.0,16.7205,0.0,5.91130,16.27320,0.0,NaN,NaN,6.0,1.0,8.96945,3.17254,0.10,0.170770,0.0,-0.865639,0.967188,1.370600,-0.474113,0.0,0.185420,0.166965,-0.031364,0.000502,0.034737,0.066760,0.092841,0.112271,0.126989,0.139319,0.151319,0.925269,-1.538810,800010000.0,1.0,-0.025989,-0.026240
2016-01-11 17:15:00,1005.19,1.17860,0.024575,1184.72,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,50.0,NaN,90582.8,NaN,281.105,NaN,15.6025,NaN,NaN,1.26987,NaN,2.0,16.0,36000.0,0.0,NaN,NaN,248.0,NaN,339.742,NaN,NaN,200.0,0.0,0.0,0.0,24.79,11.7290,11.7082,1.17860,0.024575,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.1634,82.5815,125.9420,176.635,211.388,264.632,96.6109,-14.66110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,7.78599,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.035426,35938.0,1.78453,11.3627,1.00949,506.0,2.0,8.0,7.71283,7.71283,7.71283,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-25059.400,-24853.100,NaN,NaN,1.0,6.0,18.0,93.1361,93.1361,NaN,NaN,0.02,NaN,10.10460,140.7770,5.55,NaN,NaN,NaN,-3.38077,NaN,0.0,35938.0,2495040.0,NaN,4.0,0.00000,-2.087800,0.088015,35938.0,2.665420,0.212303,1.01188,4.0,0.0,1.0,-2.087800,-2.087800,-2.063290,2.151370,NaN,2.0,2.016011e+11,4.82921,0.004938,2.151370,13.91500,0.0,864.0,8.0,141.89400,42.26850,0.0,14.05000,36000.0,61.0,13.90000,14.18000,0.793800,-5.715810,79.0,800001101.0,2912.0,6.74293,1.330950,1.323110,0.0,18.0,2.0,6.38431,2.91428,0.80,6.71714,2.0,5.13755,8.20216,2.31725,0.184685,2.0,-5.144080,800000000.0,0.0,7.944120e-14,NaN,NaN,NaN,NaN,80.0,80.0,80000.0,80000.0,NaN,NaN,12.5,NaN,0.0,7.23019,3.17506,0.80,0.055197,8.0,-1.015780,1.022250,1.57147,-0.100303,14.0,4.19732,800000000.0,29.0,9.070840e-14,0.0,248.199,36000.0,0.0,15.3374,0.0,6.74293,15.99030,0.0,NaN,NaN,9.0,1.0,7.41958,3.29553,0.80,0.142334,1.0,-0.808087,0.905006,1.348790,-0.411420,2.0,0.006510,-0.001903,-0.016020,-0.026155,-0.034194,-0.038095,-0.036559,-0.030797,-0.024244,-0.017833,-0.010944,1.183020,-1.688030,800010000.0,0.0,-0.000886,-0.000894
2016-01-11 17:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 22:45:00,1008.20,1.20023,0.024081,1210.07,0.0,1.0,37.0,1.0,1.0,-1.0,-1.0,11.0,11.0,30.0,12.0,12.0,5.3,5.3,100.0,100.0,47.0,20.0,689.0,47.4783,8.36439,209.0,-6.44248,0.0,454.787,0.0,0.0,13.8917,8.0,0.014218,3.07808,456.857,455.940,458.006,1.51095,-0.135926,0.0,456.930,19.0637,35988.0,10.0,20.0,8.05,8.8,7.9,8.45,8.05,801000000.0,134.0,NaN,95579.6,NaN,NaN,NaN,19.0845,NaN,NaN,NaN,NaN,1.82305,26.0,NaN,36000.0,0.0,12.7077,8190.0,NaN,196.751,NaN,NaN,93.38,0.0,NaN,0.0,0.0,24.79,366.9580,366.9370,1.19600,0.024218,93.6378,-0.012786,0.000972,0.011386,1.22171,2.0,-0.010466,-0.010466,-0.010466,36000.0,-6.75955,0.006657,35988.0,1.127190,1.91087,1.01935,42.0,1.0,3.0,-6.63123,-6.63123,-6.63123,2.585500e-09,24.5127,61.0400,93.0899,130.560,156.247,195.602,71.4098,-10.83670,-0.197311,0.000972,1.76042,0.175711,1.22171,205.0,2.0,6.0,-0.161505,-0.161505,-0.161505,3.209390e-11,36000.0,360.0,0.0,57.29090,5.64532,0.0,0.0,3.17006,8.50,1.82046,4.714,4.639,4.775,0.079962,-0.070828,0.0,5.67737,236.639,35988.0,0.0,0.0,13.05,13.05,7.75,8.55,8.55,801000111.0,7041.0,1.27,1.27,11.0,0.016728,36000.0,1.36052,16.7102,1.01412,63.0,1.0,4.0,56.17150,56.49300,56.17150,9999.0,9999.0,-8.892670,0.000972,35988.0,7.91917,1.22171,2.0,-7.278900,-7.278900,-7.278900,-219.673,-217.327,0.023856,0.023856,1.0,6.0,9.0,95.1059,94.1695,0.1,0.1,0.02,89.7879,1.07580,109.6360,5.55,1.658620,0.007781,0.120073,-3.03622,5.41160,0.0,36000.0,2501070.0,0.003520,4.0,0.00000,-0.339972,0.029094,36000.0,1.524520,0.063820,1.02052,7.0,0.0,1.0,-0.339972,-0.339972,-0.333135,-0.392922,-1.89740,2.0,2.024123e+11,1.78615,0.088958,-0.252685,9.05236,0.0,168.0,6.0,21.99120,3.65358,0.0,9.04000,36000.0,16.0,8.74999,9.33001,0.418553,0.448909,33.0,800000001.0,7143.0,3.51143,0.532218,0.526839,0.0,13.0,1.0,6.94616,2.91919,0.00,3.58404,0.0,2.70531,4.30896,1.17167,-0.123538,0.0,-1.179770,800000000.0,9.0,4.815250e-13,0.004224,0.003532,5.31760,5.92240,80.0,81.0,80000.0,80000.0,12.7,12.7,12.5,0.604800,0.0,9.10820,3.75220,0.00,-0.091265,4.0,-0.871973,0.779844,1.25912,0.524279,7.0,3.30665,800000000.0,99.0,1.356240e-13,0.0,280.836,36000.0,0.0,21.8181,0.0,3.51143,7.97787,0.0,-0.160594,-0.003911,13.0,1.0,9.38642,3.14090,0.00,-0.053013,0.0,-0.527875,0.511119,0.783631,0.219377,0.0,0.046420,0.048984,0.030814,0.034314,0.037230,0.040106,0.042843,0.045204,0.046974,0.048092,0.048710,0.065927,-0.196501,800000000.0,9.0,-0.101105,-0.102196

## Add *new* columns from meteo data

In [4]:
newcols = [c for c in meteo7.columns if c not in df.columns]
df = pd.concat([df, meteo7[newcols]], axis=1)
display(newcols)
df

['LW_IN_T1_47_1',
 'PA_T1_47_1',
 'PPFD_IN_T1_47_1',
 'RH_T1_47_1',
 'SW_IN_T1_47_1',
 'TA_T1_47_1',
 'SW_IN_T1_47_1_gfXG',
 'TA_T1_47_1_gfXG',
 'PPFD_IN_T1_47_1_gfXG',
 'VPD_T1_47_1',
 'VPD_T1_47_1_gfXG',
 'FLAG_VPD_T1_47_1_gfXG_ISFILLED']

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INST_AVERAGING_INT,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_HEIGHT_SA,BADM_INST_SAMPLING_INT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AGC_IRGA75_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_AIR_P_MEAN_1,CUSTOM_AIR_P_MEAN_2,CUSTOM_AIR_T_MEAN,CUSTOM_CO2_MEAN,CUSTOM_CO2_MEAN_1,CUSTOM_CO2_MEAN_2,CUSTOM_COOLER_V_IRGA72_MEAN,CUSTOM_COOLER_V_IRGA75_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_IRGA75_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FLOW_VOLRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA75_MEAN,CUSTOM_H2O_MEAN,CUSTOM_H2O_MEAN_1,CUSTOM_H2O_MEAN_2,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA75_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILE_NR,FILE_TIME_DURATION,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_SA,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,NIGHT,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA_CELL,PA_EP,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_SA,RH_EP,ROT_PITCH,ROT_YAW,ROUGHNESS_LENGTH,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SW_IN_POT,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_EP,TDEW,TIMELAG_DETECTION_METHOD,TIMESTAMP_START,TKE,TSTAR,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_SA,VPD_EP,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR,LW_IN_T1_47_1,PA_T1_47_1,PPFD_IN_T1_47_1,RH_T1_47_1,SW_IN_T1_47_1,TA_T1_47_1,SW_IN_T1_47_1_gfXG,TA_T1_47_1_gfXG,PPFD_IN_T1_47_1_gfXG,VPD_T1_47_1,VPD_T1_47_1_gfXG,FLAG_VPD_T1_47_1_gfXG_ISFILLED
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2004-09-20 10:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1070.543364,80.503701,NaN,13.300000,602.874084,13.300000,1070.543364,0.298200,0.298200,0.0
2004-09-20 11:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,881.543364,77.503701,NaN,13.390000,703.762207,13.390000,881.543364,0.346113,0.346113,0.0
2004-09-20 11:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1022.543364,75.803704,NaN,13.810000,537.947327,13.810000,1022.543364,0.382596,0.382596,0.0
2004-09-20 12:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1284.543364,71.503701,NaN,14.470000,634.747437,14.470000,1284.543364,0.470299,0.470299,0.0
2004-09-20 12:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,742.543364,72.703705,NaN,13.980000,634.747437,13.980000,742.543364,0.436409,0.436409,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 22:45:00,1008.20,1.20023,0.024081,1210.07,0.0,1.0,37.0,1.0,1.0,-1.0,-1.0,11.0,11.0,30.0,12.0,12.0,5.3,5.3,100.0,100.0,47.0,20.0,689.0,47.4783,8.36439,209.0,-6.44248,0.0,454.787,0.0,0.0,13.8917,8.0,0.014218,3.07808,456.857,455.940,458.006,1.51095,-0.135926,0.0,456.930,19.0637,35988.0,10.0,20.0,8.05,8.8,7.9,8.45,8.05,801000000.0,134.0,NaN,95579.6,NaN,NaN,NaN,19.0845,NaN,NaN,NaN,NaN,1.82305,26.0,NaN,36000.0,0.0,12.7077,8190.0,NaN,196.751,NaN,NaN,93.38,0.0,NaN,0.0,0.0,24.79,366.9580,366.9370,1.19600,0.024218,93.6378,-0.012786,0.000972,0.011386,1.22171,2.0,-0.010466,-0.010466,-0.010466,36000.0,-6.75955,0.006657,35988.0,1.127190,1.91087,1.01935,42.0,1.0,3.0,-6.63123,-6.63123,-6.63123,2.585500e-09,24.5127,61.0400,93.0899,130.560,156.247,195.602,71.4098,-10.83670,-0.197311,0.000972,1.76042,0.175711,1.22171,205.0,2.0,6.0,-0.161505,-0.161505,-0.161505,3.209390e-11,36000.0,360.0,0.0,57.2909,5.64532,0.0,0.0,3.17006,8.50,1.82046,4.714,4.639,4.775,0.079962,-0.070828,0.0,5.67737,236.639,35988.0,0.0,0.0,13.05,13.05,7.75,8.55,8.55,801000111.0,7041.0,1.27,1.27,11.0,0.016728,36000.0,1.36052,16.7102,1.01412,63.0,1.0,4.0,56.1715,56.4930,56.1715,9999.0,9999.0,-8.892670,0.000972,35988.0,7.91917,1.22171,2.0,-7.278900,-7.278900,-7.278900,-219.673,-217.327,0.023856,0.023856,1.0,6.0,9.0,95.1059,94.1695,0.1,0.1,0.02,89.7879,1.07580,109.6360,5.55,1.658620,0.007781,0.120073,-3.03622,5.41160,0.0,36000.0,2501070.0,0.003520,4.0,0.0,-0.339972,0.029094,36000.0,1.524520,0.063820,1.02052,7.0,0.0,1.0,-0.339972,-0.339972,-0.333135,-0.392922,-1.89740,2.0,2.024123e+11,1.78615,0.088958,-0.252685,9.05236,0.0,168.0,6.0,21.9912,3.65358,0.0,9.04000,36000.0,16.0,8.74999,9.33001,0.418553,0.448909,33.0,800000001.0,7143.0,3.51143,0.532218,0.526839,0.0,13.0,1.0,6.94616,2.91919,0.0,3.58404,0.0,2.70531,4.30896,1.17167,-0.123538,0.0,-1.179770,800000000.0,9.0,4.815250e-13,0.004224,0.003532,5.31760,5.92240,80.0,81.0,80000.0,80000.0,12.7,12.7,12.5,0.604800,0.0,9.10820,3.75220,0.0,-0.091265,4.0,-0.871973,0.779844,1.25912,0.524279,7.0,3.30665,800000000.0,99.0,1.356240e-13,0.0,280.836,36000.0,0.0,21.8181,0.0,3.51143,7.97787,0.0,-0.160594,-0.003911,13.0,1.0,9.38642,3.14090,0.0,-0.053013,0.0,-0.527875,0.511119,0.783631,0.219377,0.0,0.046420,0.048984,0.030814,0.034314,0.037230,0.040106,0.042843,0.045204,0.046974,0.048092,0.048710,0.065927,-0.196501,800000000.0,9.0,-0.101105,-0.102196,232.345020,94.169525,0.000000,89.787920,0.0,-0.392922,0.000000,-0.392922,0.000000,0.060608,0.060608,0.0
2024-12-31 23:15:00,1008.19,1.19504,0.024186,1204.83,0.0,1.0,37.0,1.0,1.0,-1.0,-1.0,11.0,11.0,30.0,12.0,12.0,5.3,5.3,100.0,100.0,47.0,20.0,689.0,47.4783,8.36439,209.0,10.74620,0.0,451.234,0.0,0.0,17.6100,7.9,0.099259,4.01463,453.504,451.936,454.728,2.25251,-0.518257,0.0,453.258,18.8416,35988.0,13.0,29.0,7.95,8.8,7.9,8.45,7.95,801000000.0,131.0,NaN,95582.8,NaN,NaN,NaN,18.8586,NaN,NaN,NaN,NaN,1.83377,26.0,NaN,36000.0,0.0,12.7691,8190.0,NaN,186.627,NaN,NaN,93.38,0.0,NaN,0.0,0.0,24.79,366.9790,366.9580,1.19086,0.024322,93.6404,0.005341,0.008089,0.014798,1.10398,2.0,0.004838,0.004838,0.004838,36000.0,-16.89140,0.009097,35988.0,1.201640,7.09133,0.98873,95.0,1.0,5.0,-17.08390,-17.08390,-17.08390,-1.681810e-10,20.1914,50.2793,76.6792,107.544,128.702,161.120,58.8210,-8.92632,0.082428,0.008089,2.44846,0.228357,1.10398,337.0,2.0,7.0,0.074664,0.074664,0.074664,-2.089290e-12,36000.0,360.0,0.0,39.8771,5.60563,0.0,0.0,3.17198,8.50,3.47612,4.481,4.456,4.524,0.056177,-0.431276,0.0,5.63723,234.067,35988.0,0.0,0.0,13.05,13.05,7.75,8.55,8.55,801000011.0,8230.0,1.27,1.27,11.0,0.030354,36000.0,1.45836,42.2013,1.01731,200.0,2.0,6.0,39.4645,39.1985,39.4645,9999.0,9999.0,3.710800,0.008089,35988.0,10.28030,1.10398,2.0,3.361280,3.361280,3.361280,-431.471,-419.670,0.023949,0.023949,1.0,6.0,9.0,95.0955,94.1684,0.1,0.1,0.02,81.8094,2.44005,112.5590,5.55,-3.835630,-0.002776,-0.042846,37.29780,-1.92888,0.0,36000.0,2498260.0,0.003495,4.0,0.0,-0.416967,0.010579,36000.0,1.981190,0.160463,1.02575,15.0,1.0,1.0,-0.416967,-0.416967,-0.406501,0.792661,-1.99315,2.0,2.024123e+11,3.40555,0.056032,0.776195,9.73953,0.0,393.0,7.0,31.3343,5.27288,0.0,9.63000,36000.0,30.0,9.38000,10.01000,0.602551,1.032030,55.0,800000101.0,5884.0,2.70132,0.590691,0.583230,0.0,18.0,3.0,7.55114,2.81625,0.0,2.67929,0.0,1.41390,3.78911,1.73664,0.209540,0.0,-1.035390,800000000.0,3.0,-2.047790e-13,0.004177,0.003507,5.28015,6.45421,81.0,81.0,80000.0,80000.0,12.7,12.7,12.5,1.174060,0.0,7.33225,2.63111,0.0,0.025736,8.0,-1.157120,1.099360,1.60408,-0.037385,16.0,2.49237,800000000.0,71.0,-8.926040e-15,0.0,279.175,36000.0,0.0,41.4257,0.0,2.70132,8.62258,0.0,-0.415521,0.001816,46.0,3.0,8.40327,3.34706,0.0,0.083158,0.0,-0.658706,0.746414,1.105490,-0.425976,0.0,0.032755,-0.012299,0.014113,-0.000404,-0.008502,-0.010467,-0.011853,-0.012772,-0.012849,-0.012584,-0.012387,0.115006,-0.316383,800000000.0,3.0,-0.051475,-0.052922,234.211100,94.168413,0.000000,81.809355,0.0,0.792661,0.000000,0.792661,0.000000,0.117695,0.117695,0.0

## Restrict data time range

In [5]:
keep = (df.index.year >= 2016) & (df.index.year <= 2024)
df = df[keep].copy()
df

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INST_AVERAGING_INT,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_HEIGHT_SA,BADM_INST_SAMPLING_INT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AGC_IRGA75_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_AIR_P_MEAN_1,CUSTOM_AIR_P_MEAN_2,CUSTOM_AIR_T_MEAN,CUSTOM_CO2_MEAN,CUSTOM_CO2_MEAN_1,CUSTOM_CO2_MEAN_2,CUSTOM_COOLER_V_IRGA72_MEAN,CUSTOM_COOLER_V_IRGA75_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_IRGA75_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FLOW_VOLRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA75_MEAN,CUSTOM_H2O_MEAN,CUSTOM_H2O_MEAN_1,CUSTOM_H2O_MEAN_2,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA75_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILE_NR,FILE_TIME_DURATION,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_SA,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,NIGHT,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA_CELL,PA_EP,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_SA,RH_EP,ROT_PITCH,ROT_YAW,ROUGHNESS_LENGTH,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SW_IN_POT,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_EP,TDEW,TIMELAG_DETECTION_METHOD,TIMESTAMP_START,TKE,TSTAR,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_SA,VPD_EP,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR,LW_IN_T1_47_1,PA_T1_47_1,PPFD_IN_T1_47_1,RH_T1_47_1,SW_IN_T1_47_1,TA_T1_47_1,SW_IN_T1_47_1_gfXG,TA_T1_47_1_gfXG,PPFD_IN_T1_47_1_gfXG,VPD_T1_47_1,VPD_T1_47_1_gfXG,FLAG_VPD_T1_47_1_gfXG_ISFILLED
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-01-01 00:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,-1.598717,0.0,NaN,0.057847,1.0
2016-01-01 00:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,-1.598717,0.0,NaN,0.057847,1.0
2016-01-01 01:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,-0.501368,0.0,NaN,0.047434,1.0
2016-01-01 01:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,-0.501368,0.0,NaN,0.047434,1.0
2016-01-01 02:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,-0.247269,0.0,NaN,0.028576,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 21:45:00,1008.09,1.20135,0.024060,1211.07,0.0,1.0,37.0,1.0,1.0,-1.0,-1.0,11.0,11.0,30.0,12.0,12.0,5.3,5.3,100.0,100.0,47.0,20.0,689.0,47.4783,8.36439,209.0,-2.71901,0.0,454.713,0.0,0.0,21.8712,8.4,0.036499,2.49339,456.728,455.703,458.091,1.46830,-0.315227,0.0,456.761,19.0586,35988.0,10.0,18.0,7.90,8.8,7.9,8.45,8.45,801000000.0,185.0,NaN,95606.4,NaN,NaN,NaN,19.0892,NaN,NaN,NaN,NaN,1.82424,26.0,NaN,36000.0,0.0,12.7107,8190.0,NaN,188.217,NaN,NaN,93.38,0.0,NaN,0.0,0.0,24.79,366.916,366.896,1.19728,0.024192,93.6993,-0.005229,0.001384,0.003379,1.13677,2.0,-0.004600,-0.004600,-0.004600,36000.0,-2.79421,0.005308,35988.0,1.74333,2.71905,1.01002,96.0,1.0,5.0,-2.76648,-2.76648,-2.76648,-1.205860e-09,15.5907,38.8231,59.2077,83.0397,99.3773,124.409,45.4186,-6.89245,-0.080701,0.001384,0.762184,0.052145,1.13677,109.0,2.0,6.0,-0.070992,-0.070992,-0.070992,-1.442370e-11,36000.0,360.0,0.0,9.89044,5.43899,0.0,0.0,6.31855,8.5,2.19817,4.505,4.481,4.527,0.027303,-0.234341,0.0,5.46874,227.967,35988.0,0.0,0.0,13.05,13.05,7.75,8.55,8.55,801000011.0,8364.0,1.27,1.27,11.0,0.074283,36000.0,1.35751,16.2204,1.01821,262.0,2.0,7.0,9.54442,9.71351,9.54442,9999.0,9999.0,-3.637510,0.001384,35988.0,2.35041,1.13677,2.0,-3.199880,-3.199880,-3.199880,-124.4750,-123.9000,0.023859,0.023859,1.0,6.0,9.0,95.1406,94.2118,0.1,0.1,0.02,87.2540,-3.12164,104.4270,5.55,4.53740,-0.002376,-0.036662,-27.84110,-1.65249,0.0,36000.0,2501330.0,0.003391,4.0,0.0,0.072231,0.002976,36000.0,1.212590,0.036278,1.02719,24.0,1.0,2.0,0.072231,0.072231,0.070319,-0.504794,-2.39488,2.0,2.024123e+11,0.907515,0.033306,-0.124780,9.02953,0.0,558.0,8.0,47.4164,4.16302,0.0,8.99001,36000.0,24.0,8.77999,9.24001,0.329720,0.832531,37.0,800000011.0,9492.0,2.53562,0.245203,0.241936,0.0,15.0,5.0,7.98645,2.96582,0.0,2.53414,3.0,1.94253,3.08258,0.810723,0.089660,4.0,-0.630787,800000000.0,21.0,-1.078230e-13,0.004074,0.003402,5.12555,5.87428,80.0,81.0,80000.0,80000.0,12.7,12.7,12.5,0.748736,0.0,7.19752,2.96226,0.0,-0.050510,11.0,-0.617097,0.586852,0.869688,0.262742,15.0,2.45202,800000000.0,142.0,-6.327100e-14,0.0,285.590,36000.0,0.0,20.0949,0.0,2.53562,5.67502,0.0,-0.066927,-0.001717,77.0,5.0,8.17451,4.03460,0.0,0.042876,1.0,-0.371647,0.400836,0.633562,-0.391242,1.0,0.007881,0.001751,0.011309,0.009592,0.007451,0.005559,0.004089,0.003105,0.002487,0.002084,0.001849,-0.138079,0.016036,800000000.0,21.0,-0.178429,-0.179257,232.595527,94.211806,0.0,87.254008,0.0,-0.504794,0.0,-0.504794,0.0,0.075030,0.075030,0.0
2024-12-31 22:15:00,1008.14,1.20010,0.024085,1209.87,0.0,1.0,37.0,1.0,1.0,-1.0,-1.0,11.0,11.0,30.0,12.0,12.0,5.3,5.3,100.0,100.0,47.0,20.0,689.0,47.4783,8.36439,209.0,-29.24310,0.0,453.257,0.0,0.0,19.6830,8.0,0.000689,5.29548,455.420,454.331,456.727,1.79019,-1.001810,0.0,455.331,18.9978,35988.0,21.0,36.0,8.05,8.8,7.9,8.45,8.05,801000100.0,160.0,NaN,95599.7,NaN,NaN,NaN,19.0172,NaN,NaN,NaN,NaN,1.82389,26.0,NaN,36000.0,0.0,12.7196,8190.0,NaN,191.061,NaN,NaN,93.38,0.0,NaN,0.0,0.0,24.79,366.937,366.916,1.19596,0.024219,93.6676,-0.003425,0.001672,0.014783,1.20638,1.0,-0.002839,-0.002839,-0.002839,36000.0,-9.03663,0.006239,35988.0,1.73146,3.25737,1.00450,0.0,0.0,1.0,-8.99619,-8.99619,-8.99619,1.622210e-10,20.1735,50.2348,76.6112,107.4480,128.5880,160.977,58.7689,-8.91841,-0.052852,0.001672,2.779470,0.228138,1.20638,97.0,1.0,5.0,-0.043811,-0.043811,-0.043811,1.980820e-12,36000.0,360.0,0.0,69.65120,5.53456,0.0,0.0,3.17596,8.5,1.74077,4.553,4.477,4.686,0.104346,0.393543,0.0,5.56536,231.975,35988.0,4.0,7.0,13.05,13.05,7.75,8.55,8.55,801000011.0,7854.0,1.27,1.27,11.0,0.022652,36000.0,1.81092,23.4035,1.01326,2.0,0.0,1.0,68.74620,68.73980,68.74620,9999.0,9999.0,-2.381800,0.001672,35988.0,10.28110,1.20638,1.0,-1.974340,-1.974340,-1.974340,-70.2476,-69.1854,0.023859,0.023859,1.0,6.0,9.0,95.1245,94.1890,0.1,0.1,0.02,87.4302,-0.08671,107.4580,5.55,-1.57778,0.006713,0.103588,6.56990,4.66822,0.0,36000.0,2500840.0,0.003450,4.0,0.0,-0.181061,0.039108,36000.0,1.611030,0.053344,1.01906,2.0,0.0,1.0,-0.181061,-0.181061,-0.177675,-0.296828,-2.16284,2.0,2.024123e+11,1.296370,0.148213,-0.173742,9.06736,0.0,118.0,6.0,38.4385,5.87711,0.0,9.02001,36000.0,35.0,8.77001,9.26000,0.428524,1.235990,60.0,800000111.0,7434.0,3.82572,0.388421,0.384772,0.0,23.0,2.0,6.03045,2.71161,0.0,3.75934,3.0,3.09773,4.56414,1.059910,0.148773,4.0,-1.147770,800000000.0,5.0,1.382820e-13,0.004141,0.003462,5.21435,5.96401,80.0,80.0,81100.0,81100.0,12.7,12.7,12.5,0.749662,0.0,6.96924,3.18181,0.0,-0.004525,4.0,-0.641557,0.614775,0.967594,0.078693,7.0,3.64948,800000000.0,94.0,8.538930e-15,0.0,282.067,36000.0,0.0,15.0681,0.0,3.82572,7.48419,0.0,-0.217876,-0.001061,23.0,2.0,7.64860,3.12758,0.0,-0.005845,0.0,-0.485004,0.494859,0.730129,-0.006632,0.0,0.056821,0.057545,0.030220,0.037705,0.044831,0.050684,0.054646,0.056600,0.057335,0.057556,0.057558,-0.005790,-0.118170,800000000.0,8.0,-0.316167,-0.321022,232.609777,94.189013,0.0,87.430236,0.0,-0.296828,0.0,-0.296828,0.0,0.075127,0.075127,0.0

# Sort column order

In [6]:
df = df.reindex(sorted(df.columns), axis=1)  # Sort column order
df

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INST_AVERAGING_INT,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_HEIGHT_SA,BADM_INST_SAMPLING_INT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AGC_IRGA75_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_AIR_P_MEAN_1,CUSTOM_AIR_P_MEAN_2,CUSTOM_AIR_T_MEAN,CUSTOM_CO2_MEAN,CUSTOM_CO2_MEAN_1,CUSTOM_CO2_MEAN_2,CUSTOM_COOLER_V_IRGA72_MEAN,CUSTOM_COOLER_V_IRGA75_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_IRGA75_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FLOW_VOLRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA75_MEAN,CUSTOM_H2O_MEAN,CUSTOM_H2O_MEAN_1,CUSTOM_H2O_MEAN_2,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA75_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILE_NR,FILE_TIME_DURATION,FLAG_VPD_T1_47_1_gfXG_ISFILLED,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_SA,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,LW_IN_T1_47_1,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,NIGHT,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA_CELL,PA_EP,PA_T1_47_1,PPFD_IN_T1_47_1,PPFD_IN_T1_47_1_gfXG,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_SA,RH_EP,RH_T1_47_1,ROT_PITCH,ROT_YAW,ROUGHNESS_LENGTH,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SW_IN_POT,SW_IN_T1_47_1,SW_IN_T1_47_1_gfXG,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_EP,TA_T1_47_1,TA_T1_47_1_gfXG,TDEW,TIMELAG_DETECTION_METHOD,TIMESTAMP_START,TKE,TSTAR,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_SA,VPD_EP,VPD_T1_47_1,VPD_T1_47_1_gfXG,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-01-01 00:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.598717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.057847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 00:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.598717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.057847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 01:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.501368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.047434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 01:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.501368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.047434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 02:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.247269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.028576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 21:45:00,1008.09,1.20135,0.024060,1211.07,0.0,1.0,37.0,1.0,1.0,-1.0,-1.0,11.0,11.0,30.0,12.0,12.0,5.3,5.3,100.0,100.0,47.0,20.0,689.0,47.4783,8.36439,209.0,-2.71901,0.0,454.713,0.0,0.0,21.8712,8.4,0.036499,2.49339,456.728,455.703,458.091,1.46830,-0.315227,0.0,456.761,19.0586,35988.0,10.0,18.0,7.90,8.8,7.9,8.45,8.45,801000000.0,185.0,NaN,95606.4,NaN,NaN,NaN,19.0892,NaN,NaN,NaN,NaN,1.82424,26.0,NaN,36000.0,0.0,12.7107,8190.0,NaN,188.217,NaN,NaN,93.38,0.0,NaN,0.0,0.0,24.79,366.916,366.896,1.19728,0.024192,93.6993,-0.005229,0.001384,0.003379,1.13677,2.0,-0.004600,-0.004600,-0.004600,36000.0,-2.79421,0.005308,35988.0,1.74333,2.71905,1.01002,96.0,1.0,5.0,-2.76648,-2.76648,-2.76648,-1.205860e-09,15.5907,38.8231,59.2077,83.0397,99.3773,124.409,45.4186,-6.89245,-0.080701,0.001384,0.762184,0.052145,1.13677,109.0,2.0,6.0,-0.070992,-0.070992,-0.070992,-1.442370e-11,36000.0,360.0,0.0,0.0,9.89044,5.43899,0.0,0.0,6.31855,8.5,2.19817,4.505,4.481,4.527,0.027303,-0.234341,0.0,5.46874,227.967,35988.0,0.0,0.0,13.05,13.05,7.75,8.55,8.55,801000011.0,8364.0,1.27,1.27,11.0,0.074283,36000.0,1.35751,16.2204,1.01821,262.0,2.0,7.0,9.54442,9.71351,9.54442,9999.0,9999.0,-3.637510,0.001384,35988.0,2.35041,1.13677,2.0,-3.199880,-3.199880,-3.199880,232.595527,-124.4750,-123.9000,0.023859,0.023859,1.0,6.0,9.0,95.1406,94.2118,94.211806,0.0,0.0,0.1,0.1,0.02,87.2540,87.254008,-3.12164,104.4270,5.55,4.53740,-0.002376,-0.036662,-27.84110,-1.65249,0.0,36000.0,2501330.0,0.003391,4.0,0.0,0.0,0.0,0.072231,0.002976,36000.0,1.212590,0.036278,1.02719,24.0,1.0,2.0,0.072231,0.072231,0.070319,-0.504794,-0.504794,-0.504794,-2.39488,2.0,2.024123e+11,0.907515,0.033306,-0.124780,9.02953,0.0,558.0,8.0,47.4164,4.16302,0.0,8.99001,36000.0,24.0,8.77999,9.24001,0.329720,0.832531,37.0,800000011.0,9492.0,2.53562,0.245203,0.241936,0.0,15.0,5.0,7.98645,2.96582,0.0,2.53414,3.0,1.94253,3.08258,0.810723,0.089660,4.0,-0.630787,800000000.0,21.0,-1.078230e-13,0.004074,0.003402,5.12555,5.87428,80.0,81.0,80000.0,80000.0,12.7,12.7,12.5,0.748736,0.075030,0.075030,0.0,7.19752,2.96226,0.0,-0.050510,11.0,-0.617097,0.586852,0.869688,0.262742,15.0,2.45202,800000000.0,142.0,-6.327100e-14,0.0,285.590,36000.0,0.0,20.0949,0.0,2.53562,5.67502,0.0,-0.066927,-0.001717,77.0,5.0,8.17451,4.03460,0.0,0.042876,1.0,-0.371647,0.400836,0.633562,-0.391242,1.0,0.007881,0.001751,0.011309,0.009592,0.007451,0.005559,0.004089,0.003105,0.002487,0.002084,0.001849,-0.138079,0.016036,800000000.0,21.0,-0.178429,-0.179257
2024-12-31 22:15:00,1008.14,1.20010,0.024085,1209.87,0.0,1.0,37.0,1.0,1.0,-1.0,-1.0,11.0,11.0,30.0,12.0,12.0,5.3,5.3,100.0,100.0,47.0,20.0,689.0,47.4783,8.36439,209.0,-29.24310,0.0,453.257,0.0,0.0,19.6830,8.0,0.000689,5.29548,455.420,454.331,456.727,1.79019,-1.001810,0.0,455.331,18.9978,35988.0,21.0,36.0,8.05,8.8,7.9,8.45,8.05,801000100.0,160.0,NaN,95599.7,NaN,NaN,NaN,19.0172,NaN,NaN,NaN,NaN,1.82389,26.0,NaN,36000.0,0.0,12.7196,8190.0,NaN,191.061,NaN,NaN,93.38,0.0,NaN,0.0,0.0,24.79,366.937,366.916,1.19596,0.024219,93.6676,-0.003425,0.001672,0.014783,1.20638,1.0,-0.002839,-0.002839,-0.002839,36000.0,-9.03663,0.006239,35988.0,1.73146,3.25737,1.00450,0.0,0.0,1.0,-8.99619,-8.99619,-8.99619,1.622210e-10,20.1735,50.2348,76.6112,107.4480,128.5880,160.977,58.7689,-8.91841,-0.052852,0.001672,2.779470,0.228138,1.20638,97.0,1.0,5.0,-0.043811,-0.043811,-0.043811,1.980820e-12,36000.0,360.0,0.0,0.0,69.65120,5.53456,0.0,0.0,3.17596,8.5,1.74077,4.553,4.477,4.686,0.104346,0.393543,0.0,5.56536,231.975,35988.0,4.0,7.0,13.05,13.05,7.75,8.55,8.55,801000011.0,7854.0,1.27,1.27,11.0,0.022652,36000.0,1.81092,23.4035,1.01326,2.0,0.0,1.0,68.74620,68.73980,68.74620,9999.0,9999.0,-2.381800,0.001672,35988.0,10.28110,1.20638,1.0,-1.974340,-1.974340,-1.974340,232.609777,-70.2476,-69.1854,0.023859,0.023859,1.0,6.0,9.0,95.1245,94.1890,94.189013,0.0,0.0,0.1,0.1,0.02,87.4302,87.430236,-0.08671,107.4580,5.55,-1.57778,0.006713,0.103588,6.56990,4.66822,0.0,36000.0,2500840.0,0.003450,4.0,0.0,0.0,0.0,-0.181061,0.039108,36000.0,1.611030,0.053344,1.01906,2.0,0.0,1.0,-0.181061,-0.181061,-0.177675,-0.296828,-0.296828,-0.296828,-2.16284,2.0,2.024123e+11,1.296370,0.148213,-0.173742,9.06736,0.0,118.0,6.0,38.4385,5.87711,0.0,9.02001,36000.0,35.0,8.77001,9.26000,0.428524,1.235990,60.0,800000111.0,7434.0,3.82572,0.388421,0.384772,0.0,23.0,2.0,6.03045,2.71161,0.0,3.75934,3.0,3.09773,4.56414,1.059910,0.148773,4.0,-1.147770,800000000.0,5.0,1.382820e-13,0.004141,0.003462,5.21435,5.96401,80.0,80.0,81100.0,81100.0,12.7,12.7,12.5,0.749662,0.075127,0.075127,0.0,6.96924,3.18181,0.0,-0.004525,4.0,-0.641557,0.614775,0.967594,0.078693,7.0,3.64948,800000000.0,94.0,8.538930e-15,0.0,282.067,36000.0,0.0,15.0681,0.0,3.82572,7.48419,0.0,-0.217876,-0.001061,23.0,2.0,7.64860,3.12758,0.0,-0.005845,0.0,-0.485004,0.494859,0.730129,-0.006632,0.0,0.056821,0.057545,0.030220,0.037705,0.044831,0.050684,0.054646,0.056600,0.057335,0.057556,0.057558,-0.005790,-0.118170,800000000.0,8.0,-0.316167,-0.321022

# Save to file

In [7]:
OUTNAME = "22.4_FLUXES_L1_IRGA72+METEO7_2016-2024"
filepath = save_parquet(filename=OUTNAME, data=df)
# df.to_csv(f"{OUTNAME}.csv")

Saved file 22.4_FLUXES_L1_IRGA72+METEO7_2016-2024.parquet (3.267 seconds).

# **End of notebook**.

In [8]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-08-29 12:52:08