# Wind direction checks L0 fluxes IRGA72 (2016-2025)

In [1]:
from datetime import datetime

from diive.corrections import WindDirOffset
from diive.plotting import HeatmapDateTime
from diive.core.io.files import load_parquet

In [2]:
# The merged Level-0 record written by 01_IRGA72-L0_merge_output_to_parquet_2016-2025. It lives in
# the external (untracked) data folder and is addressed by absolute path, so this notebook does not
# depend on the working directory.
SOURCEPATH = (r"F:\Sync\luhk_work\dev-data\datasets-data\dataset_ch-lae_flux_product-data"
              r"\workflow\00_L0_checks\IRGA72"
              r"\01_OPENLAG_EDDYPRO_FLUXNET_OUTPUT_IRGA72_2016-2025.parquet")
df = load_parquet(filepath=SOURCEPATH)
df

  > Loaded .parquet file
F:\Sync\luhk_work\dev-data\datasets-data\dataset_ch-lae_flux_product-data\workflow\00_L0_checks\IRGA
72\01_OPENLAG_EDDYPRO_FLUXNET_OUTPUT_IRGA72_2016-2025.parquet (0.839 seconds).

                       AIR_MV  AIR_DENSITY  AIR_RHO_CP   AIR_CP  AOA_METHOD  AXES_ROTATION_METHOD     BOWEN  BURBA_METHOD  BADM_LOCATION_LAT  BADM_LOCATION_LONG  BADM_LOCATION_ELEV  BADM_HEIGHTC  BADM_INST_SAMPLING_INT  BADM_INST_AVERAGING_INT  BADM_INST_MODEL_SA  BADM_INST_HEIGHT_SA  BADM_INST_SA_WIND_FORMAT  BADM_INST_SA_GILL_ALIGN  BADM_SA_OFFSET_NORTH  BADM_INST_MODEL_GA_CO2  BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2  BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2  ...  W_NONE_MEAS_COV  W_T_SONIC_COV_IBROM  W_T_SONIC_COV_IBROM_N1626  W_T_SONIC_COV_IBROM_N0614  W_T_SONIC_COV_IBROM_N0277  W_T_SONIC_COV_IBROM_N0133  W_T_SONIC_COV_IBROM_N0065  W_T_SONIC_COV_IBROM_N0032  W_T_SONIC_COV_IBROM_N0016  W_T_SONIC_COV_IBROM_N0008  W_T_SONIC_COV_IBROM_N0004  W_NUM_SPIKES  WD_FILTER_NREX  W_SPIKE_NREX  W_ABSLIM_NREX  W_VM97_TEST  W_LGD     W_KID    W_ZCD  W_ITC  W_ITC_TEST  WBOOST_APPLIED  WPL_APPLIED        ZL  ZL_UNCORR
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...
2016-01-11 15:15:00       NaN          NaN         NaN      NaN         NaN                   NaN       NaN           NaN                NaN                 NaN                 NaN           NaN                     NaN                      NaN                 NaN                  NaN                       NaN                      NaN                   NaN                     NaN                                 NaN                                NaN                              NaN                                 NaN                                  NaN  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           NaN             NaN           NaN            NaN          NaN    NaN       NaN      NaN    NaN         NaN             NaN          NaN       NaN        NaN
2016-01-11 15:45:00  0.025415      1.13966     1145.77  1005.36         0.0                   1.0       NaN           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                 NaN                                NaN                              NaN                                 NaN                                  NaN  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           1.0             0.0           1.0            0.0  801010000.0   1.50   7.65689      0.0    4.0         1.0             0.0          0.0  0.009173   0.009198
2016-01-11 16:15:00  0.025509      1.13546     1141.57  1005.38         0.0                   1.0       NaN           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                 NaN                                NaN                              NaN                                 NaN                                  NaN  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           0.0             0.0           0.0            0.0  801010000.0   1.55   7.31186      0.0    6.0         1.0             0.0          0.0  0.008916   0.008932
2016-01-11 16:45:00  0.025582      1.13222     1138.33  1005.40         0.0                   1.0       NaN           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                 NaN                                NaN                              NaN                                 NaN                                  NaN  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           0.0             0.0           0.0            0.0  800010000.0   0.10   8.96945      1.0    7.0         1.0             0.0          0.0 -0.024976  -0.025218
2016-01-11 17:15:00  0.025625      1.13030     1136.42  1005.41         0.0                   1.0       NaN           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                 NaN                                NaN                              NaN                                 NaN                                  NaN  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           1.0             0.0           2.0            0.0  800010000.0   0.80   7.41958      0.0    9.0         1.0             0.0          0.0 -0.000850  -0.000857
...                       ...          ...         ...      ...         ...                   ...       ...           ...                ...                 ...                 ...           ...                     ...                      ...                 ...                  ...                       ...                      ...                   ...                     ...                                 ...                                ...                              ...                                 ...                                  ...  ...              ...                  ...                        ...                        ...                        ...                        ...                        ...                        ...                        ...                        ...                        ...           ...             ...           ...            ...          ...    ...       ...      ...    ...         ...             ...          ...       ...        ...
2025-12-31 22:45:00  0.024009      1.20514     1213.13  1006.63         0.0                   1.0  0.067569           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                11.0                                1.0                             -1.0                               100.0                                  5.3  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           0.0             0.0           0.0            0.0  800000011.0   0.00  11.29880   4601.0   49.0         3.0             0.0          0.0 -0.015730  -0.030361
2025-12-31 23:15:00  0.024015      1.20467     1212.83  1006.78         0.0                   1.0  4.971290           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                11.0                                1.0                             -1.0                               100.0                                  5.3  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN          18.0             0.0          32.0            0.0  800000011.0   0.00  19.45800   7892.0   32.0         3.0             0.0          0.0  0.686305   0.697002
2025-12-31 23:45:00  0.024015      1.20467     1212.86  1006.79         0.0                   1.0  1.369620           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                11.0                                1.0                             -1.0                               100.0                                  5.3  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           1.0             0.0           2.0            0.0  800000011.0   0.00  13.98160   6271.0   20.0         2.0             0.0          0.0  2.106530   2.193120
2026-01-01 00:15:00  0.025108      1.15344     1160.99  1006.55         0.0                   1.0  1.851410           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                11.0                                1.0                             -1.0                               100.0                                  5.3  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           1.0             0.0           1.0            0.0  801000011.0   0.00  11.12460  12955.0   51.0         4.0             0.0          0.0  1.733960   1.787630
2026-01-01 00:45:00  0.025117      1.15302     1160.52  1006.50         0.0                   1.0 -0.653445           0.0            47.4783             8.36439               689.0          37.0                    20.0                     30.0                 NaN                 47.0                       NaN                      NaN                 209.0                     NaN                                11.0                                1.0                             -1.0                               100.0                                  5.3  ...              NaN                  NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN           1.0             0.0           3.0            0.0  800000011.0   0.00  15.58690   8833.0   40.0         3.0             0.0          0.0 -0.269067  -0.259494

[174836 rows x 495 columns]

In [3]:
col = 'WD'
wd = df[col].copy()

# The last run reaches a few half-hours into the next January, which would enter the analysis as a
# year of its own with almost no records in it.
LASTYEAR = 2025

# The reference year the yearly offsets are measured against is deliberately left at 2024, the year
# it was when this was last run: moving it would change every year's offset and make the results
# incomparable with the previous run, rather than adding a year to them.
REFYEARS = [2024]

# Prepare input data
wd = wd.loc[wd.index.year <= LASTYEAR]
wd = wd.dropna()

wds = WindDirOffset(winddir=wd, offset_start=-50, offset_end=50, hist_ref_years=REFYEARS, hist_n_bins=360)
yearlyoffsets_df = wds.get_yearly_offsets()
print(yearlyoffsets_df)
print(wd)
# HeatmapDateTime(series=wd).show()

# s_corrected = wds.get_corrected_wind_directions()
# print(s_corrected)
# HeatmapDateTime(series=s_corrected).show()

     YEAR  OFFSET
0  2016.0    -2.0
1  2017.0    -3.0
2  2018.0     1.0
3  2019.0     0.0
4  2020.0     1.0
5  2021.0     1.0
6  2022.0     1.0
7  2023.0     2.0
8  2024.0     0.0
9  2025.0     1.0
TIMESTAMP_MIDDLE
2016-01-11 15:45:00    241.9710
2016-01-11 16:15:00    255.9370
2016-01-11 16:45:00    253.3100
2016-01-11 17:15:00    248.1990
2016-01-11 18:15:00    243.6420
                         ...
2025-12-31 21:45:00     82.7400
2025-12-31 22:15:00     83.9291
2025-12-31 22:45:00     91.1506
2025-12-31 23:15:00     90.7695
2025-12-31 23:45:00     92.0182
Name: WD, Length: 166468, dtype: float64

In [4]:
yearlyoffsets_df

     YEAR  OFFSET
0  2016.0    -2.0
1  2017.0    -3.0
2  2018.0     1.0
3  2019.0     0.0
4  2020.0     1.0
5  2021.0     1.0
6  2022.0     1.0
7  2023.0     2.0
8  2024.0     0.0
9  2025.0     1.0

# End of notebook.

In [5]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-07-31 13:01:13