# Apply self-heating correction to open-path fluxes (NEE, 2004-2019)

# Imports

In [4]:
from datetime import datetime
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet
from diive.pkgs.flux.selfheating import ScopPhysics, ScopOptimizer, ScopApplicator

# Docstring

In [2]:
help(ScopApplicator)

Help on class ScopApplicator in module diive.pkgs.flux.selfheating:

class ScopApplicator(builtins.object)
 |  ScopApplicator(flux_type: Literal['CO2', 'H2O'], fct_unsc: pandas.core.series.Series, scaling_factors_df: pandas.core.frame.DataFrame, flux_openpath: pandas.core.series.Series, flux_closedpath: pandas.core.series.Series, classvar: pandas.core.series.Series, daytime: pandas.core.series.Series, swin: pandas.core.series.Series, ts: pandas.core.series.Series, ra: pandas.core.series.Series, rho_d: pandas.core.series.Series, latent_heat_vaporization: Optional[pandas.core.series.Series] = None)
 |
 |  Methods defined here:
 |
 |  __init__(self, flux_type: Literal['CO2', 'H2O'], fct_unsc: pandas.core.series.Series, scaling_factors_df: pandas.core.frame.DataFrame, flux_openpath: pandas.core.series.Series, flux_closedpath: pandas.core.series.Series, classvar: pandas.core.series.Series, daytime: pandas.core.series.Series, swin: pandas.core.series.Series, ts: pandas.core.series.Series, ra: pandas.core.series.Series, rho_d: pandas.core.series.Series, latent_heat_vaporization: Optional[pandas.core.series.Series] = None)
 |      Args:
 |          flux_type: "CO2" or "H2O"
 |          latent_heat_vaporization: Series of Lambda (J/mmol or J/kg depending on inputs).
 |                                    Required ONLY if flux_type="H2O" and fluxes are in W m-2
 |                                    but correction is in molar units.
 |
 |  default_format(self, ax, fontsize=9, label_color='black', txt_xlabel=False, txt_ylabel=False, txt_ylabel_units=False, width=0.5, length=3, direction='in', colors='black', facecolor='white')
 |      Apply default format to plot.
 |
 |  plot_cumulative(self, ax: <function axis at 0x000001DFAA8B4860>, title: str, which: str, df: pandas.core.frame.DataFrame, daytime_col: str)
 |
 |  plot_diel_cycles(self)
 |      Combines flux results and auxiliary variables into a single
 |      publication-quality dashboard plot with a modern, minimalist design.
 |
 |  plot_flux_analysis_dashboard(self)
 |
 |  run(self)
 |
 |  stats(self)
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  format_spines(ax, color, lw)
 |
 |  plot_series(self, ax, series, title)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

# Load data

In [7]:
SOURCEDIR = r"../../20_MERGE_DATA"
FILENAME = r"21.4_FLUXES_L1_noSHC_IRGA75+METEO7.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
print(f"Data will be loaded from the following file:\n{FILEPATH}")
df = load_parquet(filepath=FILEPATH)
df

Data will be loaded from the following file:
..\..\20_MERGE_DATA\21.4_FLUXES_L1_noSHC_IRGA75+METEO7.parquet
Loaded .parquet file ..\..\20_MERGE_DATA\21.4_FLUXES_L1_noSHC_IRGA75+METEO7.parquet (0.386 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  ...  W_T_SONIC_COV_IBROM_N1626   W_UNROT   W_U_COV  W_VM97_TEST  W_ZCD        ZL  ZL_UNCORR
TIMESTAMP_MIDDLE                                                                                                 ...
2005-01-01 00:15:00  1008.03      1.19492  0.024191     1204.51         0.0                   1.0          37.0  ...                  -0.019764  0.045938 -0.105746  800000000.0   11.0  0.118888   0.137374
2005-01-01 00:45:00  1008.11      1.19419  0.024204     1203.88         0.0                   1.0          37.0  ...                   0.022155  0.403188 -0.423825  800000000.0    5.0 -0.044524  -0.048667
2005-01-01 01:15:00  1008.17      1.19318  0.024223     1202.93         0.0                   1.0          37.0  ...                   0.009001  0.189884 -0.266300  800000000.0    7.0 -0.011929  -0.012089
2005-01-01 01:45:00  1008.24      1.19202  0.024246     1201.84         0.0                   1.0          37.0  ...                   0.016574  0.227756 -0.267261  800000000.0    9.0 -0.039767  -0.038691
2005-01-01 02:15:00  1008.29      1.19110  0.024264     1200.97         0.0                   1.0          37.0  ...                   0.030212  0.191151 -0.193863  800000000.0   13.0 -0.093878  -0.095240
...                      ...          ...       ...         ...         ...                   ...           ...  ...                        ...       ...       ...          ...    ...       ...        ...
2019-12-31 21:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN  ...                        NaN       NaN       NaN          NaN    NaN       NaN        NaN
2019-12-31 22:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN  ...                        NaN       NaN       NaN          NaN    NaN       NaN        NaN
2019-12-31 22:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN  ...                        NaN       NaN       NaN          NaN    NaN       NaN        NaN
2019-12-31 23:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN  ...                        NaN       NaN       NaN          NaN    NaN       NaN        NaN
2019-12-31 23:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN  ...                        NaN       NaN       NaN          NaN    NaN       NaN        NaN

[262944 rows x 333 columns]

# Calculate unscaled flux correction term with `ScopPhysics`

In [8]:
physics = ScopPhysics(
    flux_type="CO2",
    ta=df["TA_T1_47_1"].copy(),
    gas_density=df["CO2_MOLAR_DENSITY"].copy() * 1000,  # Requires umol m-3
    rho_a=df["AIR_DENSITY"].copy(),
    rho_v=df["VAPOR_DENSITY"].copy(),
    u=df["U"].copy(),
    c_p=df["AIR_CP"].copy(),
    ustar=df["USTAR"].copy(),
    swin=df["SW_IN_T1_47_1_gfXG"].copy(),
    lat=47.478333,  # CH–LAE
    lon=8.364389,  # CH–LAE
    utc_offset=1,
)
physics.run(correction_method_base="JAR09", gapfill=True)
results_physics_df = physics.get_results()

Warning: 38792 data points resulted in NaN due to ustar <= 0.
Aerodynamic resistance: Mean = 25.97 s m-1
Dry air density: Mean = 1.1448 kg m-3


============================================================
Starting gap-filling for
FCT_UNSC
using <class 'sklearn.ensemble._forest.RandomForestRegressor'>
============================================================

Adding new data columns ...
++ Added new columns with lagged variants for: ['TA_T1_47_1', 'AIR_CP', 'AIR_DENSITY', 'U', 'USTAR'] (lags between -1 and -1 with stepsize 1), no lagged variants for: ['FCT_UNSC']. Shifting the time series created gaps which were then filled with the nearest value.
++ Added new columns with timestamp info: ['.YEAR', '.SEASON', '.SEASON_SIN', '.SEASON_COS', '.MONTH', '.MONTH_SIN', '.MONTH_COS', '.WEEK', '.WEEK_SIN', '.WEEK_COS', '.DOY', '.DOY_SIN', '.DOY_COS', '.HOUR', '.HOUR_SIN', '.HOUR_COS', '.YEARMONTH', '.YEARDOY', '.YEARWEEK']
++ Added new column .RECORDNUMBER with record numbers from 1 to 181512.

Sanitizing timestamp ...
>>> Validating timestamp naming of timestamp column TIMESTAMP_MIDDLE ... Timestamp name OK.
>>> Converting timestamp TIMESTAMP_MIDDLE to datetime ... OK
>>> All rows have timestamp TIMESTAMP_MIDDLE, no rows removed.
>>> Sorting timestamp TIMESTAMP_MIDDLE ascending ...
>>> Removing data records with duplicate indexes ... OK (no duplicates found in timestamp index)
Detecting time resolution from timestamp TIMESTAMP_MIDDLE ... OK
   Detected 30min time resolution with HIGH confidence.
   Resolution detected from most frequent timestep (timedelta):
       from full data = None / -failed- (not used)
       from timedelta = 30min / 90% occurrence (OK)
       from progressive = 30min / data 5+5 (not used)

>>> Creating continuous 30min timestamp index for timestamp TIMESTAMP_MIDDLE between 2005-01-01 00:15:00 and 2019-03-20 12:45:00 ...
(!)Some features are incomplete and have less than 249194 values:
    --> TA_T1_47_1 (181512 values)
    --> AIR_CP (181512 values)
    --> AIR_DENSITY (181512 values)
    --> U (181512 values)
    --> USTAR (181512 values)
    --> .TA_T1_47_1-1 (181512 values)
    --> .AIR_CP-1 (181512 values)
    --> .AIR_DENSITY-1 (181512 values)
    --> .U-1 (181512 values)
    --> .USTAR-1 (181512 values)
    --> .YEAR (181512 values)
    --> .SEASON_SIN (181512 values)
    --> .SEASON_COS (181512 values)
    --> .MONTH_SIN (181512 values)
    --> .MONTH_COS (181512 values)
    --> .WEEK_SIN (181512 values)
    --> .WEEK_COS (181512 values)
    --> .DOY_SIN (181512 values)
    --> .DOY_COS (181512 values)
    --> .HOUR_SIN (181512 values)
    --> .HOUR_COS (181512 values)
    --> .YEARMONTH (181512 values)
    --> .YEARDOY (181512 values)
    --> .YEARWEEK (181512 values)
    --> .RECORDNUMBER (181512 values)
This means that not all target values can be predicted based on the full model.

Training final model ...
>>> Training model <class 'sklearn.ensemble._forest.RandomForestRegressor'> based on data between 2005-01-01 00:45:00 and 2019-03-20 11:45:00 ...
>>> Fitting model to training data ...
>>> Using model to predict target FCT_UNSC in unseen test data ...
>>> Using model to calculate permutation importance based on unseen test data ...
>>> Calculating prediction scores based on predicting unseen test data of FCT_UNSC ...
>>> Collecting results, details about training and testing can be accessed by calling .report_traintest().
>>> Done.

Gap-filling using final model ...
>>> Using final model on all data to predict target FCT_UNSC ...
>>> Using final model on all data to calculate permutation importance ...
>>> Calculating prediction scores based on all data predicting FCT_UNSC ...
>>> Predicting target FCT_UNSC where all features are available ... predicted 181512 records.
>>> Collecting results for final model ...
>>> Filling 0 missing records in target with predictions from final model ...
>>> Storing gap-filled time series in variable FCT_UNSC_gfRF ...
>>> Restoring original timestamp in results ...

Gap-filling 67682 remaining missing records in FCT_UNSC_gfRF using fallback model ...
>>> Fallback model is trained on FCT_UNSC_gfRF and timestamp info ...
++ Added new columns with timestamp info: ['.YEAR', '.SEASON', '.SEASON_SIN', '.SEASON_COS', '.MONTH', '.MONTH_SIN', '.MONTH_COS', '.WEEK', '.WEEK_SIN', '.WEEK_COS', '.DOY', '.DOY_SIN', '.DOY_COS', '.HOUR', '.HOUR_SIN', '.HOUR_COS', '.YEARMONTH', '.YEARDOY', '.YEARWEEK'] (ONLY FALLBACK)
>>> Predicting target FCT_UNSC_gfRF using fallback model ...
>>> Combining predictions from full model and fallback model ...

===================
GAP-FILLING RESULTS
===================

Model scores and feature importances were calculated from high-quality predicted targets (0 values, FCT_UNSC_gfRF where flag=1) in comparison to observed targets (181512 values, FCT_UNSC).

## TARGET
- first timestamp:  2005-01-01 00:15:00
- last timestamp:  2019-03-20 12:45:00
- potential number of values: 249194 values)
- target column (observed):  FCT_UNSC
- missing records (observed):  67682 (cross-check from flag: 67682)
- target column (gap-filled):  FCT_UNSC_gfRF  (249194 values)
- missing records (gap-filled):  0
- gap-filling flag: FLAG_FCT_UNSC_gfRF_ISFILLED
  > flag 0 ... observed targets (181512 values)
  > flag 1 ... targets gap-filled with high-quality, all features available (0 values)
  > flag 2 ... targets gap-filled with fallback (67682 values)

## FEATURE IMPORTANCES
- names of features used in model:  ['USTAR', 'U', '.HOUR_COS', 'TA_T1_47_1', '.TA_T1_47_1-1', 'AIR_DENSITY', '.DOY_COS', '.DOY_SIN', '.AIR_DENSITY-1', 'AIR_CP', '.AIR_CP-1', '.HOUR_SIN', '.RECORDNUMBER', '.WEEK_COS', '.U-1', '.USTAR-1', '.YEARDOY', '.MONTH_COS', '.WEEK_SIN', '.MONTH_SIN', '.YEARWEEK', '.YEARMONTH', '.YEAR', '.SEASON_SIN', '.SEASON_COS']
- number of features used in model:  25
- permutation importances were calculated from 1 repeats.

                PERM_IMPORTANCE  PERM_SD
USTAR                  3.387393      0.0
U                      2.038142      0.0
.HOUR_COS              0.239068      0.0
TA_T1_47_1             0.081221      0.0
.TA_T1_47_1-1          0.040151      0.0
AIR_DENSITY            0.009781      0.0
.DOY_COS               0.007098      0.0
.DOY_SIN               0.005619      0.0
.AIR_DENSITY-1         0.005502      0.0
AIR_CP                 0.003884      0.0
.AIR_CP-1              0.003400      0.0
.HOUR_SIN              0.002199      0.0
.RECORDNUMBER          0.001793      0.0
.WEEK_COS              0.001666      0.0
.U-1                   0.001172      0.0
.USTAR-1               0.001074      0.0
.YEARDOY               0.001052      0.0
.MONTH_COS             0.000938      0.0
.WEEK_SIN              0.000899      0.0
.MONTH_SIN             0.000826      0.0
.YEARWEEK              0.000676      0.0
.YEARMONTH             0.000521      0.0
.YEAR                  0.000431      0.0
.SEASON_SIN            0.000208      0.0
.SEASON_COS            0.000084      0.0

## MODEL
The model was trained on a training set with test size 25.00%.
- estimator:  RandomForestRegressor(min_samples_leaf=10, min_samples_split=20, n_estimators=3,
                      n_jobs=-1, random_state=42)
- parameters:  {'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 10, 'min_samples_split': 20, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 3, 'n_jobs': -1, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

## MODEL SCORES
- MAE:  1.569751967376161 (mean absolute error)
- MedAE:  0.7181348670912993 (median absolute error)
- MSE:  8.981428842420971 (mean squared error)
- RMSE:  2.996903208717454 (root mean squared error)
- MAXE:  46.638015970336994 (max error)
- MAPE:  0.104 (mean absolute percentage error)
- R2:  0.9414355464145003

                PERM_IMPORTANCE  PERM_SD
USTAR                  3.387393      0.0
U                      2.038142      0.0
.HOUR_COS              0.239068      0.0
TA_T1_47_1             0.081221      0.0
.TA_T1_47_1-1          0.040151      0.0
AIR_DENSITY            0.009781      0.0
.DOY_COS               0.007098      0.0
.DOY_SIN               0.005619      0.0
.AIR_DENSITY-1         0.005502      0.0
AIR_CP                 0.003884      0.0
.AIR_CP-1              0.003400      0.0
.HOUR_SIN              0.002199      0.0
.RECORDNUMBER          0.001793      0.0
.WEEK_COS              0.001666      0.0
.U-1                   0.001172      0.0
.USTAR-1               0.001074      0.0
.YEARDOY               0.001052      0.0
.MONTH_COS             0.000938      0.0
.WEEK_SIN              0.000899      0.0
.MONTH_SIN             0.000826      0.0
.YEARWEEK              0.000676      0.0
.YEARMONTH             0.000521      0.0
.YEAR                  0.000431      0.0
.SEASON_SIN            0.000208      0.0
.SEASON_COS            0.000084      0.0
{'mae': 1.569751967376161, 'medae': np.float64(0.7181348670912993), 'mse': 8.981428842420971, 'rmse': 2.996903208717454, 'mape': 0.10417504580819369, 'maxe': np.float64(46.638015970336994), 'r2': 0.9414355464145003}

In [9]:
results_physics_df.describe()

       FCT_UNSC_gfRF       FCT_UNSC             TS     TA_T1_47_1         AIR_CP  AERODYNAMIC_RESISTANCE    AIR_DENSITY  ...              U          USTAR  CO2_MOLAR_DENSITY  SW_IN_T1_47_1_gfXG  AIR_THERMAL_CONDUCTIVITY        DAYTIME  LATENT_HEAT_VAPORIZATION_J_UMOL
count  249194.000000  181512.000000  260258.000000  260258.000000  224152.000000           203306.000000  224152.000000  ...  224152.000000  224152.000000      207655.000000       262944.000000             260258.000000  262944.000000                    260258.000000
mean       15.116406      15.558114      10.609026       8.505080    1010.501247               13.106494       1.151707  ...       2.490855       0.488931       15968.675591          143.332497                  0.024845       0.446217                         0.044693
std        11.301625      12.383884       8.238440       8.210739       2.460679               11.128519       0.034942  ...       1.805885       0.306027        2355.428950          236.465935                  0.000575       0.497100                         0.000351
min         0.872043       0.872043     -16.540001     -17.200001     975.647000                0.041636       1.053700  ...       0.009557       0.007408        8483.380000            0.000000                  0.023046       0.000000                         0.043628
25%         7.228028       6.440754       4.248751       2.137056    1008.540000                5.547033       1.125710  ...       1.160550       0.252767       14741.200000            0.000000                  0.024400       0.000000                         0.044435
50%        12.069695      12.107320      10.796000       8.560000    1010.090000                9.280123       1.149870  ...       2.051600       0.432720       15549.500000            0.000000                  0.024849       0.000000                         0.044691
75%        19.652303      20.916502      16.737599      14.540000    1012.240000               16.775170       1.177020  ...       3.362165       0.658582       16448.350000          196.028532                  0.025268       1.000000                         0.044965
max       103.919409     103.919409      34.840751      33.445910    1021.290000               85.902511       1.278340  ...      13.249100       3.322560       37033.300000         1110.706662                  0.026591       1.000000                         0.045791

[8 rows x 16 columns]

# Load scaling factors from `ScopOptimizer`

In [12]:
sfdf = pd.read_csv("32_SelfHeatingCorrection_ScalingFactors_NEE.csv")
sfdf

          TIMESTAMP_MIDDLE  NEE_L3.1_L3.2_QCF_IRGA72  CO2_MOLAR_DENSITY_IRGA72  AIR_CP_IRGA72  AIR_DENSITY_IRGA72  VAPOR_DENSITY_IRGA72  U_IRGA72  ...  RH_T1_47_1_IRGA72  LE_L3.1_L3.2_QCF_IRGA72  H2O_MOLAR_DENSITY_IRGA72  NEE_L3.1_L3.2_QCF_IRGA75  CO2_MOLAR_DENSITY_IRGA75  LE_L3.1_L3.2_QCF_IRGA75  H2O_MOLAR_DENSITY_IRGA75
0      2016-05-27 00:15:00                       NaN                   14.8134        1013.51             1.10328              0.010099  2.380700  ...          63.015150                16.447500                   560.725                       NaN                   15.0989                      NaN                   560.417
1      2016-05-27 00:45:00                       NaN                   15.0169        1013.60             1.10696              0.010263  0.950929  ...          67.925517                      NaN                   569.526                       NaN                   15.3100                      NaN                   569.512
2      2016-05-27 01:15:00                       NaN                   14.9983        1013.54             1.10644              0.010181  2.205350  ...          66.753795                -5.834744                   565.637                       NaN                   15.2706                -6.041330                   565.009
3      2016-05-27 01:45:00                       NaN                   15.0355        1013.55             1.10705              0.010196  1.170180  ...          67.506901                 2.551110                   566.157                       NaN                   15.3158                 2.280256                   565.825
4      2016-05-27 02:15:00                       NaN                   15.1012        1013.59             1.10911              0.010277  0.268074  ...          70.223839               -12.065690                   570.346                       NaN                   15.3908               -16.924510                   570.299
...                    ...                       ...                       ...            ...                 ...                   ...       ...  ...                ...                      ...                       ...                       ...                       ...                      ...                       ...
27067  2017-12-11 21:45:00                       NaN                   16.4999        1009.22             1.14740              0.005345  5.951100  ...          99.864659                      NaN                   294.161                       NaN                   19.2477                      NaN                       NaN
27068  2017-12-11 22:15:00                       NaN                   16.4604        1009.31             1.14648              0.005444  6.688060  ...          99.864659                      NaN                   299.689                       NaN                   17.1550                      NaN                   302.108
27069  2017-12-11 22:45:00                       NaN                   16.4490        1009.33             1.14628              0.005483  5.815860  ...          99.864659                      NaN                   301.782                       NaN                   16.2731                      NaN                   304.261
27070  2017-12-11 23:15:00                       NaN                   16.5297        1009.16             1.14953              0.005275  6.391870  ...          99.864659                      NaN                   290.160                       NaN                   16.2659                      NaN                   292.735
27071  2017-12-11 23:45:00                   4.32377                   16.6301        1009.11             1.15119              0.005220  6.725140  ...          99.864659                      NaN                   287.169                       NaN                   15.1207                      NaN                   289.695

[27072 rows x 17 columns]

# Correct open-path fluxes with `ScopApplicator`

In [14]:
applicator = ScopApplicator(
    flux_type="CO2",
    fct_unsc=results_physics_df["FCT_UNSC_gfRF"],
    ts=results_physics_df["TS"],
    ra=results_physics_df["AERODYNAMIC_RESISTANCE"],
    rho_d=results_physics_df["DRY_AIR_DENSITY"],
    scaling_factors_df=sfdf,
    flux_openpath=df["FC"].copy(),
    flux_closedpath=df["NEE_L3.1_L3.2_QCF_IRGA72"].copy(),
    classvar=df["USTAR"].copy(),
    daytime=results_physics_df["DAYTIME"].copy(),
    swin=df["SW_IN_T1_47_1_gfXG"].copy()
)
applicator.run()

KeyError: 'NEE_L3.1_L3.2_QCF_IRGA72'

In [ ]:
applicator.stats()

In [ ]:
applicator.plot_flux_analysis_dashboard();

In [ ]:
applicator.plot_diel_cycles()

# Scaling factors table

In [ ]:
scaling_factors_df

# Save to file

In [ ]:
filename = "32_SelfHeatingCorrection_ScalingFactors_NEE"
df.to_csv(f"{filename}.csv", index=True)

# ✅END OF NOTEBOOK

In [ ]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")